DROP TABLE IF EXISTS API_USERS;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE API_USERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN DEFAULT TRUE
);

INSERT INTO API_USERS (USERNAME, PASSWORD, ROLE, ENABLED) VALUES
  ('admin', '$2a$12$5V23F3bTfmLzfHi31YYdj.dZxFHy4yK1wsGpRsDWaD1WTaP0O291O', 'ADMIN',  true),
  ('user1', '$2a$12$rMX07j/lsvhmOKf8e47BwuZV23sV0rpglvemX.rUxlW7gnsz1oKeK', 'READ', true),
  ('user2', '$2a$12$OAV66S0goskvkHeuHaln..RaVOheuRH7J0t7jph5M4CusM9gg1mLy', 'WRITE', true);

CREATE TABLE EMPLOYEE (
  ID BIGINT(19) AUTO_INCREMENT  PRIMARY KEY,
  DEPARTMENT VARCHAR(255) NOT NULL,
  EMPLOYEE_NAME VARCHAR(255) NOT NULL,
  EMPLOYEE_SALARY INTEGER(10) NOT NULL
);

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_NAME, EMPLOYEE_SALARY) VALUES
  ('Claims', 'James', 300000),
  ('Finance', 'John', 450000),
  ('Legal', 'Kohari', 360000);